// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiT4d6n_T_ugowDn016o2TmPRzDhUe4xA',
    appId: '1:61698020665:web:02c4b346d9416fd928c4e8',
    messagingSenderId: '61698020665',
    projectId: 'notification-c9869',
    authDomain: 'notification-c9869.firebaseapp.com',
    storageBucket: 'notification-c9869.appspot.com',
    measurementId: 'G-N4T4S6TFZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTkyOFsWfoAktBbruIN7gaPvGdNRFqcj4',
    appId: '1:61698020665:android:6e31bc10d8d8ef2728c4e8',
    messagingSenderId: '61698020665',
    projectId: 'notification-c9869',
    storageBucket: 'notification-c9869.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlr3xUX4w5o-9gzxJrKHAkwjPNbT6k-iE',
    appId: '1:61698020665:ios:2fb5d8ea71ba63a128c4e8',
    messagingSenderId: '61698020665',
    projectId: 'notification-c9869',
    storageBucket: 'notification-c9869.appspot.com',
    iosBundleId: 'com.babe.flutterBabe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlr3xUX4w5o-9gzxJrKHAkwjPNbT6k-iE',
    appId: '1:61698020665:ios:2fb5d8ea71ba63a128c4e8',
    messagingSenderId: '61698020665',
    projectId: 'notification-c9869',
    storageBucket: 'notification-c9869.appspot.com',
    iosBundleId: 'com.babe.flutterBabe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiT4d6n_T_ugowDn016o2TmPRzDhUe4xA',
    appId: '1:61698020665:web:f250070312901c3128c4e8',
    messagingSenderId: '61698020665',
    projectId: 'notification-c9869',
    authDomain: 'notification-c9869.firebaseapp.com',
    storageBucket: 'notification-c9869.appspot.com',
    measurementId: 'G-DJH1XJV6E2',
  );
}
